# Generated by Django 3.1 on 2020-09-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_curso', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('max_activity', models.IntegerField()),
            ],
        ),
    ]
